"""Count the automated tests in every public repo and write stats.json.

Two kinds of tests are counted:
  * unit / integration tests: test cases in the usual test files of each
    language (Java/Kotlin @Test, Dart test()/testWidgets(), Python def test_*,
    JS/TS it()/test(), C# [Fact]/[Test]..., Go func Test*, Rust #[test]);
  * load tests: Grafana k6 scripts. Each k6 scenario counts as one load test
    (a script without `scenarios` counts as one).

The site (index.html) reads stats.json to fill every project's "Tests" value
and the "Automated tests" total, so pushing new tests to any repo updates the
portfolio by itself.

Usage:
  python tools/count_tests.py                 # scan GitHub (GH_TOKEN optional)
  python tools/count_tests.py --local DIR     # scan local clones in DIR/<repo>
"""
import argparse
import datetime
import io
import json
import os
import re
import tarfile
import urllib.request

USER = 'Ahshika'
SKIP = {'ahshika.github.io', 'ahshika'}
OUT = 'stats.json'
MAX_FILE = 2_000_000
IGNORED_DIRS = {'node_modules', 'build', 'dist', '.dart_tool', '.gradle', 'vendor', 'venv', '.venv',
                'site-packages', 'Pods', 'third_party', '.git', '__pycache__', 'coverage', '.next', 'out'}

K6_IMPORT = re.compile(r'''(from\s+['"]k6(/[\w/-]*)?['"]|require\(\s*['"]k6(/[\w/-]*)?['"]\s*\))''')
PATTERNS = {
    'dart': re.compile(r'^\s*(?:test|testWidgets)\s*\(', re.M),
    'py': re.compile(r'^\s*(?:async\s+)?def\s+test\w*\s*\(', re.M),
    'js': re.compile(r'^\s*(?:it|test)(?:\.only|\.skip|\.concurrent)?\s*\(|^\s*(?:it|test)\.each\b', re.M),
    'java': re.compile(r'@Test(?![A-Za-z])'),
    'cs': re.compile(r'\[\s*(?:Fact|Theory|Test|TestMethod|TestCase)\b'),
    'go': re.compile(r'^func\s+Test\w*\s*\(', re.M),
    'rs': re.compile(r'#\[\s*(?:tokio::)?test\s*\]'),
}
JS_EXT = ('.js', '.mjs', '.cjs', '.ts', '.tsx', '.jsx')
# Placeholder tests generated by Android Studio / Capacitor templates, not real tests.
TEMPLATE_TESTS = re.compile(r'^Example(Unit|Instrumented)Test\.(java|kt)$')


def in_test_dir(parts):
    return any(p in ('test', 'tests', '__tests__', 'spec', 'androidTest', 'integration_test') for p in parts)


def classify(path):
    """Returns the pattern key for a test file, 'k6?' for possible k6 scripts, or None."""
    parts = path.split('/')
    if any(p in IGNORED_DIRS for p in parts[:-1]):
        return None
    name = parts[-1]
    if TEMPLATE_TESTS.match(name):
        return None
    low = name.lower()
    if low.endswith('.dart'):
        return 'dart' if low.endswith('_test.dart') or in_test_dir(parts) else None
    if low.endswith('.py'):
        return 'py' if low.startswith('test_') or low.endswith('_test.py') or in_test_dir(parts) else None
    if low.endswith(JS_EXT):
        if '.test.' in low or '.spec.' in low or in_test_dir(parts):
            return 'js'
        return 'k6?'
    if low.endswith(('.java', '.kt')):
        return 'java' if in_test_dir(parts) or re.search(r'Tests?\.(java|kt)$', name) else None
    if low.endswith('.cs'):
        return 'cs'
    if low.endswith('_test.go'):
        return 'go'
    if low.endswith('.rs'):
        return 'rs'
    return None


def k6_scenarios(text):
    if not K6_IMPORT.search(text):
        return 0
    executors = len(re.findall(r'\bexecutor\s*:', text))
    return executors or 1


def count_file(path, text, totals):
    kind = classify(path)
    if kind is None:
        return
    if kind in ('k6?', 'js'):
        load = k6_scenarios(text)
        if load:
            totals['load'] += load
            return
        if kind == 'k6?':
            return
    totals['unit'] += len(PATTERNS[kind].findall(text))


def scan_local(root):
    totals = {'unit': 0, 'load': 0}
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in IGNORED_DIRS]
        for fn in filenames:
            full = os.path.join(dirpath, fn)
            rel = os.path.relpath(full, root).replace(os.sep, '/')
            if classify(rel) is None or os.path.getsize(full) > MAX_FILE:
                continue
            with open(full, encoding='utf-8', errors='ignore') as f:
                count_file(rel, f.read(), totals)
    return totals


def api(url, raw=False):
    headers = {'Accept': 'application/vnd.github+json', 'User-Agent': 'portfolio-stats'}
    if os.environ.get('GH_TOKEN'):
        headers['Authorization'] = 'Bearer ' + os.environ['GH_TOKEN']
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers), timeout=120) as r:
        data = r.read()
    return data if raw else json.loads(data)


def scan_remote(repo):
    totals = {'unit': 0, 'load': 0}
    data = api(f'https://api.github.com/repos/{USER}/{repo["name"]}/tarball/{repo["default_branch"]}', raw=True)
    with tarfile.open(fileobj=io.BytesIO(data), mode='r:gz') as tar:
        for m in tar:
            if not m.isfile() or m.size > MAX_FILE:
                continue
            rel = m.name.split('/', 1)[1] if '/' in m.name else m.name   # drop "<owner>-<repo>-<sha>/"
            if classify(rel) is None:
                continue
            count_file(rel, tar.extractfile(m).read().decode('utf-8', 'ignore'), totals)
    return totals


def public_repos():
    repos = api(f'https://api.github.com/users/{USER}/repos?per_page=100&sort=created&direction=asc')
    return [r for r in repos if not r['fork'] and not r['archived'] and not r['private']
            and r['name'].lower() not in SKIP]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--local', help='folder that contains local clones named like the repos')
    args = ap.parse_args()

    if args.local:
        names = sorted(d for d in os.listdir(args.local)
                       if os.path.isdir(os.path.join(args.local, d)) and d.lower() not in SKIP)
        results = {n: scan_local(os.path.join(args.local, n)) for n in names}
    else:
        results = {r['name']: scan_remote(r) for r in public_repos()}

    repos = {}
    for name, t in sorted(results.items(), key=lambda kv: kv[0].lower()):
        repos[name] = {'unit': t['unit'], 'load': t['load'], 'total': t['unit'] + t['load']}
    totals = {k: sum(r[k] for r in repos.values()) for k in ('unit', 'load', 'total')}

    old = {}
    if os.path.exists(OUT):
        with open(OUT, encoding='utf-8') as f:
            old = json.load(f)
    changed = old.get('repos') != repos
    if changed:
        stats = {'updated': datetime.date.today().isoformat(), 'totals': totals, 'repos': repos}
        with open(OUT, 'w', encoding='utf-8') as f:
            json.dump(stats, f, indent=2)
            f.write('\n')

    for name, r in repos.items():
        print(f'{name:30} unit={r["unit"]:4}  load={r["load"]:3}')
    print(f'{"TOTAL":30} unit={totals["unit"]:4}  load={totals["load"]:3}  => {totals["total"]} tests'
          + ('' if changed else '  (unchanged)'))
    if os.environ.get('GITHUB_OUTPUT'):
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write(f'changed={"true" if changed else "false"}\n')


if __name__ == '__main__':
    main()
